project:
  type: website
  output-dir: _site

website:
  title: "Estadística IV"
  site-url: https://benjaminbaeza.github.io/stadisticawebfinal/
  
  navbar:
    right:
      - href: programa.qmd
        text: Programación
      - text: Clases
        menu:
          - text: Modulo 1 · Presentación del curso
            href: Modulos/clase1.qmd
          - text: Modulo 2 · Estadística descriptiva
            href: Modulos/clase2.qmd
          - text: Modulo 3 . Análisis de Correspondencias Simple (AC) y Múltiple (ACM)
            href: Modulos/clase3.qmd
          - text: Modulo 4 . Análisis de Componentes Principales (PCA) Parte -1
            href: Modulos/clase4.qmd 
          - text: Modulo 5 . Análisis de Componentes Principales (PCA) Parte -2
            href: Modulos/clase5.qmd 
          - text: Modulo 6 . Análisis Factorial Exploratorio (EFA)
            href: Modulos/clase6.qmd
          - text: Modulo 7 . Repaso PCA y EFA
            href: Modulos/clase7.qmd
          - text: Modulo 8 . Aplicación EFA y Trabajo Final
            href: Modulos/clase8.qmd
          

      - text: Prácticos
        menu: 
          - text: Practico 1: Creación de tablas de contingencia en R y
cálculo e interpretación de X 
          - href: Practicos.qmd
        
      - href: ayudantia.qmd
        text: Ayudantias
        
      

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    toc-title: "En esta página"
    smooth-scroll: true
    css: styles.css

