project:
  type: website
  output-dir: _site

website:
  title: "Estadística IV"
  site-url: https://benjaminbaeza.github.io/stadisticawebfinal/
  
  navbar:
    right:
      - href: programa.qmd
        text: Programación
      - text: Clases
        menu:
          - text: Modulo 1 · Presentación del curso
            href: clase1.qmd
          - text: Modulo 2 · Estadística descriptiva
            href: clase2.qmd
      - href: Practicos.qmd
        text: Prácticos
      - href: ayudantia.qmd
        text: Ayudantias
        
      

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
