project:
  type: website

website:
  title: "Estadística IV"

  navbar:
    right:
      - href: index.qmd
        text: Inicio

      - href: programa.qmd
        text: Programación

      - text: Clases
        menu:
          - text: Clase 1 · Presentación del curso
            href: clase1.qmd
          - text: Clase 2 · Estadística descriptiva
            href: clase2.qmd
          - text: Clase 3 · Regresión
            href: clase_03.qmd

      - href: Practicos.qmd
        text: Prácticos

format:
  html:
    theme: cosmo
    toc: false
